language: node_js
sudo: false
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-veams' ]; then cd .. && eval "mv $currentfolder generator-veams" && cd generator-veams; fi

git:
  submodules: false
# whitelist
branches:
  only:
    - master
    - dev