language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-prototype' ]; then cd .. && eval "mv $currentfolder generator-prototype" && cd generator-prototype; fi

git:
  submodules: false
# whitelist
branches:
  only:
    - master