language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-pg' ]; then cd .. && eval "mv $currentfolder generator-pg" && cd generator-pg; fi

git:
  submodules: false
# whitelist
branches:
  only:
    - master
    - dev